### ISSUE TITLE
Sailawaynmea-plugin and opencpn MacbookPro M2 

### ISSUE THREAD

**Issue by rametep66** [Rasbats/SailawayNMEA_pi#4]
hello,

I installed the sailaway to nmea plugin

but it is not yet compatible with the Apple M architecture
do you think it would be possible to have an update in this direction

Thank you for your involvement Kind regards

Contents/PlugIns/SailawayNMEA_pi/libSailawayNMEA_pi.dylib, 0x0002): tried: '/Applications/OpenCPN.app/Contents/PlugIns/SailawayNMEA_pi/libSailawayNMEA_pi.dylib' (mach-o file, but is an incompatible architecture

**Comment by Rasbats** [comment]
Thanks for the report. Will take a look.

**Comment by Rasbats** [comment]
Updated and compiled for the Mac OS:
[https://cloudsmith.io/~mike-rossiter/repos/sailawaynmea-alpha/packages/](https://cloudsmith.io/~mike-rossiter/repos/sailawaynmea-alpha/packages/)
Search for Darwin!
@rametep66 ... could you test. If it works we will update the catalog.

**Comment by rametep66** [comment]
Hello,

Import OK config OK 
Congratulation mille Merci
Best Regard

**Comment by rametep66** [comment]
Hello,
just to say it works,
but the data and buttons are invisible
<img width="205" alt="Capture d’écran 2024-11-25 à 22 05 55" src="https://github.com/user-attachments/assets/642afa82-9787-49af-b769-2ce8f7cf95d1">
Best Regard

**Comment by Rasbats** [comment]
Does changing the colour scheme of the Mac make any difference? 
Have you seen this with any other plugins?

**Comment by Rasbats** [comment]
Changed the button face/text and re-compiled. Now on Cloudsmith.

**Comment by rametep66** [comment]
hi,
now it's works good
there is a problem accessing backend.sailaway.word/cgi-bin/sailaway
do you have a contact at sailaway Richard maybe

**Comment by Rasbats** [comment]
Good. This will be useful for other plugins.
No contact with Sailaway. I have not upgraded to Sailaway v3. I get NMEA but the boat is not moving. Intend getting the new version to test if it works with the plugin.

**Comment by rametep66** [comment]
No need for plugin in v3 NMEA server is integrated
but many players use it with the Vendée Globe

**Comment by Rasbats** [comment]
In view of V3 NMEA server this plugin has now been removed from the catalog.
